/// Flutter icons DiabetesIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DiabetesIcons
///      fonts:
///       - asset: fonts/DiabetesIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DiabetesIcons {
  DiabetesIcons._();

  static const _kFontFam = 'DiabetesIcons';

  static const IconData blood_count_test = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData scale__1__1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData scale__2_ = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData weighing = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData scale = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData scale__1_ = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData blood_count_test__1_ = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData scaler = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData blood_count_test__3_ = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData blood_count_test__2_ = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData blood_pressure = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData pharmacy__2_ = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData pharmacy__1_ = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData pharmacy = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData drugs__1_ = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData drugs = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData injection = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData medicine = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData blood_pressure__1_ = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData blood_pressure__2_ = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData dinner__4_ = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData dinner__3_ = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData dinner__2_ = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData dinner__1_ = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData dinner = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData plate__2_ = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData plate__1_ = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData plate = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData breakfast__2_ = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData breakfast__1_ = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData breakfast = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData instruction__4_ = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData instruction__3_ = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData instruction__2_ = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData instruction__1_ = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData instruction = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData pouring__2_ = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData pouring__1_ = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData pouring = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData planning__3_ = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData planning__2_ = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData planning__1_ = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData planning = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData dinner__5_ = const IconData(0xe82b, fontFamily: _kFontFam);
}
